#version: '3.8'

services:
  web:
    image: php:8.2-apache
    build: .
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./:/var/www/html
    environment:
      - AMOCRM_CLIENT_ID=${AMOCRM_CLIENT_ID}
      - AMOCRM_CLIENT_SECRET=${AMOCRM_CLIENT_SECRET}
      - AMOCRM_REDIRECT_URI=${AMOCRM_REDIRECT_URI}
      - AMOCRM_SUBDOMAIN=${AMOCRM_SUBDOMAIN}
    command: bash -c "sed -ri 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf
      && a2enmod rewrite
      && docker-php-entrypoint apache2-foreground"